print("Введите имя:")
name = input()
print("Введите возраст:")
age = input()
print("Введите место жительства:")
place = input()
print("Вас зовут:", name,".", "Вам", age, "лет",".", "Вы живете в", place)